# Define a string
string = " Hello, Python World! "

# Print the original string
print(f"Original string: '{string}'")

# Using various string methods
print(f"strip(): '{string.strip()}'")
print(f"lstrip(): '{string.lstrip()}'")
print(f"rstrip(): '{string.rstrip()}'")
print(f"lower(): '{string.lower()}'")
print(f"upper(): '{string.upper()}'")
print(f"capitalize(): '{string.capitalize()}'")
print(f"title(): '{string.title()}'")
print(f"swapcase(): '{string.swapcase()}'")
print(f"replace('Python', 'Programming'): '{string.replace('Python', 'Programming')}'")
print(f"find('Python'): {string.find('Python')}")
print(f"index('Python'): {string.index('Python')}")
print(f"count('o'): {string.count('o')}")
print(f"startswith(' Hello'): {string.startswith(' Hello')}")
print(f"endswith('World! '): {string.endswith('World! ')}")
print(f"split(): {string.split()}")
print(f"join(['Hello', 'Python']): {' '.join(['Hello', 'Python'])}")
print(f"center(30, '*'): '{string.center(30, '*')}'")
print(f"ljust(30, '-'): '{string.ljust(30, '-')}'")
print(f"rjust(30, '-'): '{string.rjust(30, '-')}'")
print(f"isalnum(): {string.isalnum()}")
print(f"isalpha(): {string.isalpha()}")
print(f"isdigit(): {string.isdigit()}")
print(f"islower(): {string.islower()}")
print(f"isupper(): {string.isupper()}")
print(f"isspace(): {string.isspace()}")
print(f"istitle(): {string.istitle()}")
print(f"encode(): {string.encode()}")
print(f"expandtabs(4): '{string.expandtabs(4)}'")
print(f"zfill(25): '{string.zfill(25)}'")
print(f"partition('Python'): {string.partition('Python')}")
print(f"rpartition('Python'): {string.rpartition('Python')}")
print(f"splitlines(): {string.splitlines()}")
